# Site settings
title: Breaking the limits 2026
email: "supereddington2026 dot oaca at inaf.it"
url: https://breakingthelimits.github.io/supereddington2026
description: "Conference about Super-Eddington accretion. Sardinia, Italy, June 2026"


baseurl: /supereddington2026

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Matteo Bachetti

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/supereddy2018
#  - title: facebook
#    url: https://www.facebook.com/supereddington2018

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: <!--more-->
